export const SITE_NAME = "TeknolojiAkışı";
export const SITE_DESCRIPTION =
  "Teknoloji dünyasından en güncel haberler, incelemeler ve analizler";
export const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://teknolojiakisi.com.tr";

export const DEFAULT_PAGE_SIZE = 12;
export const ADMIN_PAGE_SIZE = 20;

export const CATEGORY_COLORS: Record<string, string> = {
  yapay_zeka: "#8B5CF6",
  mobil: "#3B82F6",
  web: "#10B981",
  donanim: "#F59E0B",
  yazilim: "#EC4899",
  oyun: "#EF4444",
  bilim: "#06B6D4",
  guvenlik: "#F97316",
  sosyal_medya: "#6366F1",
  otomotiv: "#84CC16",
  genel: "#6B7280",
};

export const DEFAULT_SOURCES = [
  // Türkçe kaynaklar
  {
    name: "Donanım Haber",
    url: "https://www.donanimhaber.com",
    feedUrl: "https://www.donanimhaber.com/rss/tum",
    type: "rss",
    language: "tr",
    priority: 8,
    categoryName: "donanim",
  },
  {
    name: "ShiftDelete",
    url: "https://shiftdelete.net",
    feedUrl: "https://shiftdelete.net/feed",
    type: "rss",
    language: "tr",
    priority: 8,
    categoryName: "genel",
  },
  {
    name: "Webtekno",
    url: "https://www.webtekno.com",
    feedUrl: "https://www.webtekno.com/rss.xml",
    type: "rss",
    language: "tr",
    priority: 7,
    categoryName: "genel",
  },
  {
    name: "Teknoblog",
    url: "https://teknoblog.com",
    feedUrl: "https://teknoblog.com/feed",
    type: "rss",
    language: "tr",
    priority: 7,
    categoryName: "genel",
  },
  {
    name: "CHIP Online",
    url: "https://www.chip.com.tr",
    feedUrl: "https://www.chip.com.tr/rss",
    type: "rss",
    language: "tr",
    priority: 6,
    categoryName: "genel",
  },
  // İngilizce kaynaklar
  {
    name: "The Verge",
    url: "https://www.theverge.com",
    feedUrl: "https://www.theverge.com/rss/index.xml",
    type: "rss",
    language: "en",
    priority: 9,
    categoryName: "genel",
  },
  {
    name: "TechCrunch",
    url: "https://techcrunch.com",
    feedUrl: "https://techcrunch.com/feed",
    type: "rss",
    language: "en",
    priority: 9,
    categoryName: "web",
  },
  {
    name: "Ars Technica",
    url: "https://arstechnica.com",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
    type: "rss",
    language: "en",
    priority: 8,
    categoryName: "genel",
  },
  {
    name: "Wired",
    url: "https://www.wired.com",
    feedUrl: "https://www.wired.com/feed/rss",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "bilim",
  },
  {
    name: "9to5Mac",
    url: "https://9to5mac.com",
    feedUrl: "https://9to5mac.com/feed",
    type: "rss",
    language: "en",
    priority: 8,
    categoryName: "mobil",
  },
  {
    name: "9to5Google",
    url: "https://9to5google.com",
    feedUrl: "https://9to5google.com/feed",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "mobil",
  },
  {
    name: "GSMArena",
    url: "https://www.gsmarena.com",
    feedUrl: "https://www.gsmarena.com/rss-news-reviews.php3",
    type: "rss",
    language: "en",
    priority: 8,
    categoryName: "mobil",
  },
  // Ek kaynaklar - AI / Yazılım / İnternetten para kazanma
  {
    name: "VentureBeat AI",
    url: "https://venturebeat.com/category/ai",
    feedUrl: "https://venturebeat.com/category/ai/feed",
    type: "rss",
    language: "en",
    priority: 9,
    categoryName: "yapay_zeka",
  },
  {
    name: "The Verge AI",
    url: "https://www.theverge.com/ai-artificial-intelligence",
    feedUrl: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    type: "rss",
    language: "en",
    priority: 9,
    categoryName: "yapay_zeka",
  },
  {
    name: "TechCrunch AI",
    url: "https://techcrunch.com/category/artificial-intelligence",
    feedUrl: "https://techcrunch.com/category/artificial-intelligence/feed",
    type: "rss",
    language: "en",
    priority: 9,
    categoryName: "yapay_zeka",
  },
  {
    name: "Android Authority",
    url: "https://www.androidauthority.com",
    feedUrl: "https://www.androidauthority.com/feed",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "mobil",
  },
  {
    name: "XDA Developers",
    url: "https://www.xda-developers.com",
    feedUrl: "https://www.xda-developers.com/feed",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "mobil",
  },
  {
    name: "Hacker News",
    url: "https://news.ycombinator.com",
    feedUrl: "https://hnrss.org/frontpage",
    type: "rss",
    language: "en",
    priority: 8,
    categoryName: "yazilim",
  },
  {
    name: "The Register",
    url: "https://www.theregister.com",
    feedUrl: "https://www.theregister.com/headlines.atom",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "genel",
  },
  {
    name: "Tom's Hardware",
    url: "https://www.tomshardware.com",
    feedUrl: "https://www.tomshardware.com/feeds/all",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "donanim",
  },
  {
    name: "Bleeping Computer",
    url: "https://www.bleepingcomputer.com",
    feedUrl: "https://www.bleepingcomputer.com/feed",
    type: "rss",
    language: "en",
    priority: 8,
    categoryName: "guvenlik",
  },
  {
    name: "ZDNet",
    url: "https://www.zdnet.com",
    feedUrl: "https://www.zdnet.com/news/rss.xml",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "genel",
  },
  {
    name: "TechRadar",
    url: "https://www.techradar.com",
    feedUrl: "https://www.techradar.com/rss",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "genel",
  },
  {
    name: "Engadget",
    url: "https://www.engadget.com",
    feedUrl: "https://www.engadget.com/rss.xml",
    type: "rss",
    language: "en",
    priority: 7,
    categoryName: "genel",
  },
  {
    name: "Donanım Arşivi",
    url: "https://www.donanimalsivi.com",
    feedUrl: "https://www.donanimalsivi.com/rss",
    type: "rss",
    language: "tr",
    priority: 6,
    categoryName: "donanim",
  },
];

export const BOT_AUTHORS = [
  {
    name: "Teknoloji Editörü",
    slug: "teknoloji-editoru",
    bio: "Teknoloji dünyasındaki en son gelişmeleri sizler için takip ediyor.",
    specialty: "Genel Teknoloji",
    isBot: true,
  },
  {
    name: "Mobil Dünyası",
    slug: "mobil-dunyasi",
    bio: "Akıllı telefon ve mobil teknoloji alanındaki yenilikleri yakından takip ediyorum.",
    specialty: "Mobil Teknoloji",
    isBot: true,
  },
  {
    name: "Yapay Zeka Muhabiri",
    slug: "yapay-zeka-muhabiri",
    bio: "Yapay zeka ve makine öğrenmesi alanındaki gelişmeleri analiz ediyorum.",
    specialty: "Yapay Zeka",
    isBot: true,
  },
  {
    name: "Oyun & Eğlence",
    slug: "oyun-eglence",
    bio: "Oyun dünyasından haberler, incelemeler ve teknoloji eğlence kesişimi.",
    specialty: "Oyun",
    isBot: true,
  },
];

export const DEFAULT_CATEGORIES = [
  { name: "Yapay Zeka", slug: "yapay-zeka", color: "#8B5CF6", sortOrder: 1 },
  { name: "Mobil", slug: "mobil", color: "#3B82F6", sortOrder: 2 },
  { name: "Web", slug: "web", color: "#10B981", sortOrder: 3 },
  { name: "Donanım", slug: "donanim", color: "#F59E0B", sortOrder: 4 },
  { name: "Yazılım", slug: "yazilim", color: "#EC4899", sortOrder: 5 },
  { name: "Oyun", slug: "oyun", color: "#EF4444", sortOrder: 6 },
  { name: "Bilim", slug: "bilim", color: "#06B6D4", sortOrder: 7 },
  { name: "Güvenlik", slug: "guvenlik", color: "#F97316", sortOrder: 8 },
  { name: "Sosyal Medya", slug: "sosyal-medya", color: "#6366F1", sortOrder: 9 },
  { name: "Otomotiv", slug: "otomotiv", color: "#84CC16", sortOrder: 10 },
  { name: "Genel", slug: "genel", color: "#6B7280", sortOrder: 99 },
];
